job-service:
  url: http://job:8082
review-service:
  url: http://review:8083
company-service:
  url: http://company:8081

spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/reviewdb
    url: jdbc:postgresql://ep-patient-unit-a4qp1vev-pooler.us-east-1.aws.neon.tech/review-service?sslmode=require
    username: review-service_owner
    password: ${postgresql_pass}
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: "${app.jwtSecret}"
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0



server:
  port: 8083

app:
  message: "Hello review service!"
  jwtSecret: M9I6vAzZgxgTVKe9ZzMZy7OLs/ly1G7d0ozukNY6hGE=

eureka:
  client:
    service-url:
      defaultZone: http://servicereg:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true


logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 3MB
      max-history: 3 #Day

